import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import ChakraUIProvider from "@/components/providers/ChakraUIProvider";
import Navigation from "@/components/navbar";

export const metadata = {
  title: "Boilerplate Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* automatski povlaci, ne mora da se naznacava */}
      {/* <head>
        <link rel="icon" href="/favicon.ico" />
      </head> */}
      <body className={inter.className}>
        <ChakraUIProvider>
          <Navigation />
          {children}</ChakraUIProvider>
      </body>
    </html>
  );
}
